### ISSUE TITLE
Replace file_get_contents with WordPress filesystem functions.

### ISSUE THREAD

**Issue by benlk** [WPBuddy/largo#1526]
As part of #844:

> inc/avatars/admin.php:59:                               @file_get_contents($_FILES[LARGO_AVATAR_INPUT_NAME]['tmp_name'])

Relevant reading: https://developer.wordpress.org/reference/functions/wp_filesystem/

**Comment by benlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [replace file_get_contents with WordPress filesystem calls](https://trello.com/c/ijKOmlaq/41-replace-filegetcontents-with-wordpress-filesystem-calls)

**Comment by omnisite** [comment]
@benlk I can pick this one up, if you want?

**Comment by benlk** [comment]
Please do!

**Comment by omnisite** [comment]
@benlk Ok, will do!

**Comment by omnisite** [comment]
@benlk Do I branch of of trunk or develop (or another branch)?

**Comment by omnisite** [comment]
@benlk I have my changes ready but do not seem to be able to push my branch. Permission denied.
